routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Front\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [DashboardController::class, 'index'])->name('home');
    Route::resource('product', ProductController::class)->except(['show']);
    Route::get('sub_category/{id}', [ProductController::class, 'subCategory'])->name('sub-category');
});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        @can('product-list')
            <div class="col-4">
                <div class="card">
                    <div class="card-body bg-success rounded text-white">
                        <h3>
                            Products
                        </h3>
                        <h1 class="text-end">
                            {{ $product_count }}
                        </h1>
                        <div class="text-center">
                            <a class="nav-link text-white" href="{{ route('product.index') }}">
                                More Info
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @endcan
        <div class="col-4">
            <div class="card">
                <div class="card-body bg-primary rounded text-white">
                    <h3>
                        Users
                    </h3>
                    <h1 class="text-end">
                        {{ $user_count }}
                    </h1>
                    <div class="text-center">
                        <a class="nav-link text-white" href="{{ route('home') }}">
                            More Info
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection