routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Front\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [DashboardController::class, 'index'])->name('home');
    Route::resource('product', ProductController::class)->except(['show']);
    Route::get('sub_category/{id}', [ProductController::class, 'subCategory'])->name('sub-category');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'category_id',
        'sub_category_id',
        'price',
        'description',
        'image',
        'status'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucwords($value);
    }

    public function setDescriptionAttribute($value)
    {
        $this->attributes['description'] = $value ?? '';
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function subCategory()
    {
        return $this->belongsTo(Category::class, 'sub_category_id', 'id');
    }

    public function getImageAttribute($value)
    {
        $file['url'] = asset("storage/products/$value");
        $file['thumb'] = asset("storage/products/thumb/$value");

        return (object) $file;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\FileUploadTrait;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Facades\Gate;

class ProductController extends Controller
{
    use FileUploadTrait;

    public function index()
    {
        abort_if(!Gate::allows('product-list'), 401);

        $products = Product::latest()->get();

        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        abort_if(!Gate::allows('product-create'), 401);

        $categories = Category::orderBy('id', 'desc')->where('parent_id', 0)->get()->pluck('name', 'id')->prepend('Please Select', '');
        $sub_categories = ['' => 'Please Select'];

        return view('admin.product.create', compact('categories', 'sub_categories'));
    }

    public function store(Request $request)
    {
        abort_if(!Gate::allows('product-create'), 401);

        $request->validate([
            'name' => ['required', 'unique:products', 'max:200'],
            'price' => ['required'],
            'status' => ['required'],
            'image' => ['required'],
            'category_id' => ['required'],
            'sub_category_id' => ['required'],
            'description' => ['nullable'],
        ]);

        $productData = $this->imageUpload($request, [], 'products')->all();

        Product::create($productData);

        return redirect()->route('product.index')->with('success', 'Product saved successfully');
    }

    public function edit(Product $product)
    {
        abort_if(!Gate::allows('product-edit'), 401);

        $categories = Category::orderBy('id', 'desc')->where('parent_id', 0)->get()->pluck('name', 'id');
        $sub_categories = Category::where('parent_id', $product->category_id)->get()->pluck('name', 'id');

        return view('admin.product.edit', compact('product', 'categories', 'sub_categories'));
    }

    public function update(Request $request, Product $product)
    {
        abort_if(!Gate::allows('product-edit'), 401);

        $request->validate([
            'name' => ['required', 'unique:products,name,' . $product->id, 'max:200'],
            'price' => ['required'],
            'status' => ['required'],
            'image' => ['nullable'],
            'category_id' => ['required'],
            'sub_category_id' => ['required'],
            'description' => ['nullable'],
        ]);

        $productData = $this->imageUpload($request, $product->toArray(), 'products')->all();

        $product->update($productData);

        return redirect()->route('product.index')->with('success', 'Product updated successfully');
    }

    public function destroy(Product $product)
    {
        abort_if(!Gate::allows('product-delete'), 401);

        $product->delete();

        return back()->with('success', 'Product deleted successfully');
    }

    public function subCategory($id)
    {
        $sub_categories = Category::where('parent_id', $id)->get()->pluck('name', 'id')->prepend('Please Select', '');

        return response()->json([
            'success' => true,
            'msg' => 'Category Found',
            'html' => view('partials.sub-category', compact('sub_categories'))->render(),
        ]);
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header h4">
            Create Product
        </div>

        <div class="card-body">
            {!! Form::open(['method' => 'POST', 'route' => ['product.store'], 'autocomplete' => 'off', 'files' => true]) !!}
            <div class="row">
                <div class="form-group col-6">
                    <label class="required">
                        Name
                    </label>
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                </div>

                <div class="form-group col-6">
                    <label>
                        Category
                    </label>
                    {!! Form::select('category_id', $categories, old('category_id'), ['class' => 'form-control', 'required' => '', 'id' => 'optCategory']) !!}
                </div>

                <div class="form-group col-6" id="subCategory">
                    @include('partials.sub-category', ['sub_categories' => $sub_categories])
                </div>

                <div class="form-group col-6">
                    <label class="required">
                        Price
                    </label>
                    {!! Form::text('price', old('price'), ['class' => 'form-control', 'maxlength' => '10', 'onkeypress' => 'return isFloat(event)', 'required' => '']) !!}
                </div>

                <div class="form-group col-6">
                    @include('partials.single-image-upload', [
                    'input_name' => 'image',
                    'lable_name' => 'Image',
                    'image_view_name' => 'image_view',
                    'image_error_name' => 'image_error',
                    'required' => 'required',
                    'image_url' => ''
                    ])
                </div>

                <div class="form-group col-6">
                    <label class="required">
                        Status
                    </label>
                    <div class="form-check">
                        {!! Form::radio('status', old('status', 1), true, ['class' => 'form-check-input', 'required' => '', 'id' => 'rbActive']) !!}
                        <label class="required" for="rbActive">
                            Active
                        </label>
                    </div>
                    <div class="form-check">
                        {!! Form::radio('status', old('status', 0), false, ['class' => 'form-check-input', 'required' => '', 'id' => 'rbInactive']) !!}
                        <label class="required" for="rbInactive">
                            Inactive
                        </label>
                    </div>
                </div>

                <div class="form-group col-12">
                    <label class="required">
                        Description
                    </label>
                    {!! Form::textarea('description', old('description'), ['class' => 'form-control ckeditor', 'placeholder' => '']) !!}
                </div>

                <div class="form-group text-right col-12 mt-4">
                    <button class="btn btn-success float-end" type="submit">
                        Save
                    </button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $('#optCategory').on('change', function() {
            $.ajax({
                type: 'get',
                url: "{{ url('sub_category') }}/" + this.value,
            }).done(function(res) {
                $('.preloader').css('height', '0px');

                if (res.success) {
                    $('#subCategory').empty().html(res.html);

                    toastr.success(res.msg);
                } else {
                    toastr.error(res.msg);
                }
            });
        });
    </script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            Edit Prodict

            <a class="btn btn-secondary float-end" href="{{ route('product.index') }}">
                Back
            </a>
        </div>

        <div class="card-body">
            {!! Form::model($product, ['method' => 'PUT', 'route' => ['product.update', $product->id], 'autocomplete' => 'off', 'files' => true]) !!}
            <div class="row">
                <div class="form-group col-6">
                    <label class="required">
                        Name
                    </label>
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                </div>

                <div class="form-group col-6">
                    <label>
                        Category
                    </label>
                    <select class="form-control" name="category_id" id="optCategory">
                        @foreach ($categories as $key => $category)
                            <option value="{{ $key }}" {{ $key == $product->category->id ? 'selected' : '' }}>
                                {{ $category }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group col-6" id="subCategory">
                    <label>
                        Category
                    </label>
                    <select class="form-control" name="sub_category_id">
                        @foreach ($sub_categories as $key => $category)
                            <option value="{{ $key }}" {{ $key == $product->subCategory->id ? 'selected' : '' }}>
                                {{ $category }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group col-6">
                    <label class="required">
                        Price
                    </label>
                    {!! Form::text('price', old('price'), ['class' => 'form-control', 'maxlength' => '10', 'onkeypress' => 'return isFloat(event)', 'required' => '']) !!}
                </div>

                <div class="form-group col-6">
                    @include('partials.single-image-upload', [
                    'input_name' => 'image',
                    'lable_name' => 'Image',
                    'image_view_name' => 'image_view',
                    'image_error_name' => 'image_error',
                    'required' => '',
                    'image_url' => $product->image->url
                    ])
                </div>

                <div class="form-group col-6">
                    <label class="required">
                        Status
                    </label>
                    <div class="form-check">
                        {!! Form::radio('status', old('status', '1'), false, ['class' => 'form-check-input', 'required' => '', 'id' => 'rbActive']) !!}
                        <label class="required" for="rbActive">
                            Active
                        </label>
                    </div>
                    <div class="form-check">
                        {!! Form::radio('status', old('status', '0'), false, ['class' => 'form-check-input', 'required' => '', 'id' => 'rbInactive']) !!}
                        <label class="required" for="rbInactive">
                            Inactive
                        </label>
                    </div>
                </div>

                <div class="form-group col-12">
                    <label class="required">
                        Description
                    </label>
                    {!! Form::textarea('description', old('description', $product->description), ['class' => 'form-control ckeditor', 'placeholder' => '']) !!}
                </div>

                <div class="form-group text-right col-12 mt-4">
                    <button class="btn btn-warning float-end" type="submit">
                        Update
                    </button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $('#optCategory').on('change', function() {
            $.ajax({
                type: 'get',
                url: "{{ url('sub_category') }}/" + this.value,
            }).done(function(res) {
                $('.preloader').css('height', '0px');

                if (res.success) {
                    $('#subCategory').empty().html(res.html);

                    toastr.success(res.msg);
                } else {
                    toastr.error(res.msg);
                }
            });
        });
    </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="card">
        <div class="card-header h4">
            Products List

            @can('product-create')
                <a class="btn btn-success float-end" href="{{ route('product.create') }}">
                    Add Product
                </a>
            @endcan
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover datatable">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Category
                            </th>
                            <th>
                                Sub Category
                            </th>
                            <th>
                                Image
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                status
                            </th>
                            @canany(['product-update', 'product-delete'])
                                <th class="action">
                                    Actions
                                </th>
                            @endcanany
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($products as $key => $item)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    {{ $item->name }}
                                </td>
                                <td>
                                    {{ $item->category->name }}
                                </td>
                                <td>
                                    {{ $item->subCategory->name }}
                                </td>
                                <td class="text-center">
                                    <img src="{{ $item->image->url }}" alt="{{ $item->name }}" width="120" height="80"
                                        class="rounded">
                                </td>
                                <td>
                                    {{ $item->price }}
                                </td>
                                <td>
                                    @if ($item->status)
                                        <span class="badge bg-success">Active</span>
                                    @else
                                        <span class="badge bg-danger">Inactive</span>
                                    @endif
                                </td>
                                @canany(['product-update', 'product-delete'])
                                    <td>
                                        @can('product-edit')
                                            <a href="{{ route('product.edit', [$item->id]) }}"
                                                class="my-2 btn-sm btn btn-warning">
                                                Edit
                                            </a>
                                        @endcan
                                        @can('product-delete')
                                            <form action="{{ route('product.destroy', $item->id) }}" method="POST"
                                                onsubmit="return confirm('Are you sure, want to delete?');"
                                                style="display: inline-block;">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="my-2 btn-sm btn btn-danger">
                                                    Delete
                                                </button>
                                            </form>
                                        @endcan
                                    </td>
                                @endcanany
                            </tr>
                        @empty
                            <tr>
                                <td colspan="10" class="text-center">
                                    No recored found
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('.datatable').DataTable({
                "pageLength": 50
            });
        });
    </script>
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="card">
        <div class="card-header">
            {{ trans('global.show') }} Service

            <a class="btn btn-secondary float-right" href="{{ route('admin.service.index') }}">
                {{ trans('global.back') }}
            </a>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            Title
                        </th>
                        <td>
                            {{ $service->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Slug
                        </th>
                        <td>
                            {{ $service->slug }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Price
                        </th>
                        <td>
                            {{ $service->price }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Image
                        </th>
                        <td>
                            <img src="{{ $service->image_url }}" alt="{{ $service->title }}" width="200" height="120">
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Therapy
                        </th>
                        <td>
                            @forelse ($service->therapies as $row)
                                <span class="badge badge-pill badge-primary h6 mr-2 px-3 py-2 text-center">
                                    {{ $row->therapy->title }}
                                </span>
                            @empty
                            @endforelse
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Description
                        </th>
                        <td>
                            {!! $service->description !!}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection